/*
    * stateNameByFipsCode.js
    * Created by Max Kendall 02/05/2021
*/

export const stateNameByFipsId = {
    "01": "Alabama",
    "02": "Alaska",
    "04": "Arizona",
    "05": "Arkansas",
    "06": "California",
    "08": "Colorado",
    "09": "Connecticut",
    10: "Delaware",
    11: "District of Columbia",
    12: "Florida",
    13: "Georgia",
    15: "Hawaii",
    16: "Idaho",
    17: "Illinois",
    18: "Indiana",
    19: "Iowa",
    20: "Kansas",
    21: "Kentucky",
    22: "Louisiana",
    23: "Maine",
    24: "Maryland",
    25: "Massachusetts",
    26: "Michigan",
    27: "Minnesota",
    28: "Mississippi",
    29: "Missouri",
    30: "Montana",
    31: "Nebraska",
    32: "Nevada",
    33: "New Hampshire",
    34: "New Jersey",
    35: "New Mexico",
    36: "New York",
    37: "North Carolina",
    38: "North Dakota",
    39: "Ohio",
    40: "Oklahoma",
    41: "Oregon",
    42: "Pennsylvania",
    44: "Rhode Island",
    45: "South Carolina",
    46: "South Dakota",
    47: "Tennessee",
    48: "Texas",
    49: "Utah",
    50: "Vermont",
    51: "Virginia",
    53: "Washington",
    54: "West Virginia",
    55: "Wisconsin",
    56: "Wyoming",
    60: "American Samoa",
    66: "Guam",
    69: "Northern Mariana Islands",
    72: "Puerto Rico",
    78: "U.S. Virgin Islands"
};

export const fipsIdByStateName = {
    alabama: "01",
    alaska: "02",
    arizona: "04",
    arkansas: "05",
    california: "06",
    colorado: "08",
    connecticut: "09",
    delaware: "10",
    "district of columbia": "11",
    florida: "12",
    georgia: "13",
    hawaii: "15",
    idaho: "16",
    illinois: "17",
    indiana: "18",
    iowa: "19",
    kansas: "20",
    kentucky: "21",
    louisiana: "22",
    maine: "23",
    maryland: "24",
    massachusetts: "25",
    michigan: "26",
    minnesota: "27",
    mississippi: "28",
    missouri: "29",
    montana: "30",
    nebraska: "31",
    nevada: "32",
    "new hampshire": "33",
    "new jersey": "34",
    "new mexico": "35",
    "new york": "36",
    "north carolina": "37",
    "north dakota": "38",
    ohio: "39",
    oklahoma: "40",
    oregon: "41",
    pennsylvania: "42",
    "rhode island": "44",
    "south carolina": "45",
    "south dakota": "46",
    tennessee: "47",
    texas: "48",
    utah: "49",
    vermont: "50",
    virginia: "51",
    washington: "53",
    "west virginia": "54",
    wisconsin: "55",
    wyoming: "56",
    "american samoa": "60",
    guam: "66",
    "northern mariana islands": "69",
    "puerto rico": "72",
    "us virgin islands": "78"
};
