
def primary_nav(nav_name):
     return '//div[@class = "nav-dropdown__parent-label" and text() = "{}"]/parent::button'.format(nav_name)

def sub_nav(nav_name):
    return '//a[@class = "nav-children__link " and text() = "{}"]'.format(nav_name)

def filter(filter_name):
    return '//button[@class="filter-toggle__button " and @title="{}"]'.format(filter_name)

def fy(year):
    return '//input[@class="fy-option-checkbox" and @value="FY {}"]'.format(year)

def input_by_id(id):
    return '//input[@id="{}"]'.format(id)

def input_by_class(class_name):
    return '//input[@class="{}"]'.format(class_name)

def input_by_placeholder(placeholder):
    return '//input[@placeholder="{}"]'.format(placeholder)

def checkbox_by_value(value):
    return '//input[@value="{}"]'.format(value)

def search_results(category):
    return '//button[@title="Show {}" and not(@disabled)]/div[@class="tab-content"]//div[@class="count-badge  active"]'.format(
        category)

def tab(name):
    return '//button[@class="visualization-type-tab " and @aria-label="{}"]'.format(name)

def search_tab(name):
    return '//*[@id="results-section-table"]/div[2]/button[{}]'.format(name)

def time_graph(path):
    return '//*[@id="results-section-time"]/div[2]/span/div/*[local-name()="svg"]{}'.format(path)

XPATH_DICT = {
    #buttons

    "Submit Search button": '//*[@id="main-content"]/div/div[1]/div/div[2]/div/button[1]',#'//button[@class="submit-button" and text() = "Submit Search" and not(@disabled)]',
    "Try our Spending Explorer":'//*[@class="feature-spending-explorer__button"]',

    #Nav
    "Award Search top nav":primary_nav("Award Search"),
    "Advanced Search":sub_nav("Advanced Search"),

    #fy
    "2018 fy checkbox": fy("2018"),


    "Location filter":filter("Location"),
    "Agency filter":filter("Agency"),
    "Time Period filter":filter("Time Period"),
    "Recipient filter": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div/button',

    #inputs:
    "Zip Code": input_by_id("location-picker-zip"),
    "Awarding Agency": '//input[@type="text" and @placeholder = "Awarding Agency"]',
    "Recipient input": input_by_class("recipient-input"),
    "Keyword input": input_by_class("keyword-input"),
    "Award ID input": input_by_class("award-id-input"),
    "Funding Agency": input_by_placeholder("Funding Agency"),
    "CFDA": input_by_placeholder("e.g., 93.778 - Medical Assistance Program"),
    # "NAICS": input_by_placeholder("e.g., 336411 - Aircraft Manufacturing"),
    "NAICS": '//*[@class="geo-entity-dropdown__input"]',
    # "PSC": input_by_placeholder("e.g., 1510 - Aircraft, Fixed Wing"),
    "PSC": '//*[@class="geo-entity-dropdown__input"]',
    "TAS": '//*[@class="geo-entity-dropdown__input"]',

    "CFDA filter": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[10]/div[1]/button',
    "PSC filter": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[12]/div/button',

    "shown filter button": '//button[@class="shown-filter-button"]',
    "Active filter label": '//*[@id="top-filter-bar-title"]',
    "filter group 1 title": '//*[@id="main-content"]/div/div[2]/div[3]/div[1]/div/div[2]/div/div/div/div[1]/div',
    "filter item 1": '//*[@id="main-content"]/div/div[2]/div[3]/div[1]/div/div[2]/div/div/div/div[2]/div/div/div/div',

    "Date range": '//*[@id="filter-date-range-tab"]',
    "start date input": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div[1]/form/div[1]/div[1]/label/input',
    "start date icon": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div/form/div[1]/div[1]/a',

    "calendar previous": '//span[@aria-label="Previous Month"]',
    "calendar 2 previous": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div/form/div[2]/div[2]/div/div/div[1]/span[1]',
    "calendar next": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div/form/div[2]/div[2]/div/div/div[1]/span[2]',
    "calendar day 1": '//div[@class="DayPicker-Day" and @tabindex="0"]',
    "calendar today": '//div[@class="DayPicker-Day DayPicker-Day--today"]',
    "calendar today selected": '//div[@class="DayPicker-Day DayPicker-Day--selected DayPicker-Day--today"]',
    "end date input": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div[1]/form/div[2]/div[1]/label/input',
    "end date icon": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div/form/div[2]/div[1]/a',
    "date submit": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div/form/button',
    "date error message": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div[2]',
    "calendar body": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[2]/div[2]/div/div/form/div[2]/div[2]/div/div/div[2]/div/div[3]/div[1]/div[1]',


    "Contracts check": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[1]/div/div/div/label/input',
    "Contract toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[1]/div/div/div/button',
    "BPAs": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[1]/ul/li[1]/label/input',
    "Purchase orders": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[1]/ul/li[2]/label/input',
    "Delivery orders": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[1]/ul/li[3]/label/input',
    "Definitive contracts": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[1]/ul/li[4]/label/input',

    "Contract IDVs checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/div/div/div/label/input',
    "Contract IDVs toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/div/div/div/button',
    "GWAC": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/ul/li[1]/label/input',
    "IDC multi agency contract": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/ul/li[2]/label/input',
    "IDC requirements": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/ul/li[3]/label/input',
    "IDC indefinite quantity": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/ul/li[4]/label/input',
    "IDC definite quantity": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/ul/li[5]/label/input',
    "FSS": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/ul/li[6]/label/input',
    "BOA": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/ul/li[7]/label/input',
    "BPA IDVs": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[2]/ul/li[8]/label/input',


    "Grants checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[3]/div/div/div/label/input',
    "Grants toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[3]/div/div/div/button',
    "Block grant": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[3]/ul/li[1]/label/input',
    "Formula grant": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[3]/ul/li[2]/label/input',
    "Project grant": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[3]/ul/li[3]/label/input',
    "Cooperative agreement": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[3]/ul/li[4]/label/input',

    "Direct Payments checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[4]/div/div/div/label/input',
    "Direct Payments toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[4]/div/div/div/button',
    "Direct Payment unrestricted use": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[4]/ul/li[1]/label/input',
    "Direct Payment specified use": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[4]/ul/li[2]/label/input',

    "Loans checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[5]/div/div/div/label/input',
    "Loans toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[5]/div/div/div/button',
    "Direct loans": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[5]/ul/li[1]/label/input',
    "Guaranteed/Insured loans": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[5]/ul/li[2]/label/input',

    "Other checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[6]/div/div/div/label/input',
    "Other toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[6]/div/div/div/button',
    "Insurance": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[6]/ul/li[1]/label/input',
    "Other financial assistance": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[3]/div[2]/div/ul/li[6]/ul/li[2]/label/input',



    #outputs
    "Search Results for contracts":search_results("Contracts"),
    "Top Banner":'//*[@id="main-focus"]',

    #homepage
    "three pane": '//div[@class="feature-pane"]',
    "arrow": '//button[@class="hero-button__button"]',
    "Spending explorer content": '//div[@class="feature-spending-explorer"]',
    "homepage dropdown": '//button[@class="feature-dropdown__button "]',
    "Awards content": '//div[@class="feature-award-search"]',
    "advanced screenshot": '(//*[@class="feature-award-search__image-wrapper"]//img)[1]',
    "keyword screenshot": '(//*[@class="feature-award-search__image-wrapper"]//img)[2]',
    "advanced search option": '//a[@href="#/search" and @class="feature-dropdown-item__link"]',
    "keyword search option": '//a[@href="#/keyword_search" and @class="feature-dropdown-item__link"]',
    "glossary button": '//*[@id="header-glossary-button"]',

    #homepage download section
    "Award Data Archive": '//div[@class="homepage-download__button-label" and text()="Award Data Archive"]',
    "Custom Award Data": '//div[@class="homepage-download__button-label" and text()="Custom Award Data"]',
    "Custom Account Data": '//div[@class="homepage-download__button-label" and text()="Custom Account Data"]',
    "Agency Submission Files": '//div[@class="homepage-download__button-label" and text()="Agency Submission Files"]',
    "Database Download": '//div[@class="homepage-download__button-label" and text()="Database Download"]',
    "API": '//div[@class="homepage-download__button-label" and text()="API"]',
    "Join the conversation": '//a[@class="homepage-community__link"]',

    "Visit our community page button": '//a[@class="homepage-community__link"]',
    "community header": '//header[@class="header"]',
    "community footer": '//footer[@class="footer"]' ,
    "community navigation": '//nav[@class="user-nav"]',

    #spending explorer
    "spending explorer header": '//*[@id="app"]/div[1]/div/div[1]/header/nav/div/div[4]/ul/li[1]/a',
    "spending explorer selection header": '//*[@id="main-content"]/div/div/div[2]/div[1]/div/div[1]/h2',
    "spending explorer landing header": '//*[@id="main-content"]/div/div[1]/h2',
    "spending explorer fy header": '//*[@id="detail-header"]/div[1]/h2',
    "spending explorer title": '//*[@id="main-focus"]',
    "spending feature box 2": '//div[@class="explorer-treemap"]/*[local-name() = "svg"]/*[local-name() = "g"][2]',
    "spending feature box": '//div[@class="explorer-treemap"]/*[local-name() = "svg"]/*[local-name() = "g"][1]',
    "spending table icon": '//*[@title="Show results in a table"]',
    "spending table link": '//*[@class="go-deeper-link"][1]',
    "Start over": '//a[@class="start-over-button"]',
    "spending explorer fy drop": '//*[@id="main-content"]/div/div/div[1]/div[2]/div/div/div/div[2]/button',
    "spending explorer obligated amount": '//*[@id="main-content"]/div/div/div[1]/div[3]/ul/span/li/button/div[2]/div[2]',
    "spending explorer fy 2018": '//*[@id="main-content"]/div/div/div[1]/div[2]/div/div/div/div[2]/ul/li[2]/button',
    "spending explorer quarter": '//*[@id="main-content"]/div/div/div[1]/div[2]/ul/li[4]/button',
    "spending explorer Q1": '//*[@id="main-content"]/div/div/div[1]/div[2]/ul/li[1]/button',
    "spending explorer Q2": '//*[@id="main-content"]/div/div/div[1]/div[2]/ul/li[2]/button',
    "spending explorer Q3": '//*[@id="main-content"]/div/div/div[1]/div[2]/ul/li[3]/button',
    "spending explorer Q4": '//*[@id="main-content"]/div/div/div[1]/div[2]/ul/li[4]/button',
    "Budget Box": '//*[@id="main-content"]/div/div[2]/div[1]',
    "Budget Symbol": '//*[@id="main-content"]/div/div[2]/div[1]/div[1]/*[local-name()="svg"]',
    "Budget Header": '//*[@id="main-content"]/div/div[2]/div[1]/h2',
    "Budget Text": '//*[@id="main-content"]/div/div[2]/div[1]/div[2]',
    "Budget Button": '//*[@id="main-content"]/div/div[2]/div[1]/a',
    "Agency Box": '//*[@id="main-content"]/div/div[2]/div[2]',
    "Agency Symbol": '//*[@id="main-content"]/div/div[2]/div[2]/div[1]/*[local-name()="svg"]',
    "Agency Header": '//*[@id="main-content"]/div/div[2]/div[2]/h2',
    "Agency Text": '//*[@id="main-content"]/div/div[2]/div[2]/div[2]',
    "Agency Button": '//*[@id="main-content"]/div/div[2]/div[2]/a',
    "Agency Pagination Totals": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/div[1]/div',
    "Agency Pagination First": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/div[1]/ul/li[1]/button',
    "Agency Pagination Last": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/div[1]/ul/li[6]/button',
    "Agency Pagination 1": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/div[1]/ul/li[2]/button',
    "Agency Pagination 2": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/div[1]/ul/li[3]/button',
    "Agency Pagination 5": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/div[1]/ul/li[5]/button',
    "Object Box": '//*[@id="main-content"]/div/div[2]/div[3]',
    "Object Symbol": '//*[@id="main-content"]/div/div[2]/div[3]/div[1]/*[local-name()="svg"]',
    "Object Header": '//*[@id="main-content"]/div/div[2]/div[3]/h2',
    "Object Text": '//*[@id="main-content"]/div/div[2]/div[3]/div[2]',
    "Object Button": '//*[@id="main-content"]/div/div[2]/div[3]/a',

    "Explorer Dropdown": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[1]/div/div[1]/div[2]/button',
    "Budget Dropdown": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[1]/div/div[1]/div[2]/ul/li[1]/button',
    "Agency Dropdown": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[1]/div/div[1]/div[2]/ul/li[2]/button',
    "Class Dropdown": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[1]/div/div[1]/div[2]/ul/li[3]/button',

    "Explorer View Button": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[1]/div/div[2]/button[1]',
    "Explorer Table Button": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[1]/div/div[2]/button[2]',
    "exp heading": '//*[@id="detail-header"]/div[1]/h2',
    "Explorer Table Value 1 Name": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/table/tbody/tr[1]/td[1]/div/div',
    "Explorer Table Value 1 Amount": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/table/tbody/tr[1]/td[2]/div/div',
    "Explorer Start Over": '//*[@id="main-content"]/div/div/div[1]/div[1]/a',
    "Explorer Tree Go Back": '//*[@id="main-content"]/div/div/div[2]/div[2]/button',
    "Explorer Name Sort Ascending": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/table/thead/tr/td[1]/div/div/div/div[2]/button[1]',
    "Explorer Amount Sort Ascending": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/table/thead/tr/td[2]/div/div/div/div[2]/button[1]',
    "Explorer Percent Sort Descending": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[3]/div/table/thead/tr/td[3]/div/div/div/div[2]/button[2]',
    "Agency Page Header": '//*[@id="main-content"]/div[1]/h3[1]',

    "budget glossary": '//*[@id="main-content"]/div/div[2]/div[1]/h2/a',
    "agency glossary": '//*[@id="main-content"]/div/div[2]/div[2]/h2/a',
    "object glossary": '//*[@id="main-content"]/div/div[2]/div[3]/h2/a',

    "budget start": '//*[@id="main-content"]/div/div[2]/div[1]/a',
    "agency start": '//*[@id="main-content"]/div/div[2]/div[2]/a',
    "object start": '//*[@id="main-content"]/div/div[2]/div[3]/a',

    "spending explorer load message": '//div[@class="explorer-detail-content__loading"]',

    "view dropdown" : '//*[@id="main-content"]/div/div/div[2]/div[2]/div[2]/div/div[1]/div[2]/button/div[2]',
    "budget drop": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[2]/div/div[1]/div[2]/ul/li[1]/button',
    "agency drop": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[2]/div/div[1]/div[2]/ul/li[2]/button',
    "object drop": '//*[@id="main-content"]/div/div/div[2]/div[2]/div[2]/div/div[1]/div[2]/ul/li[3]/button',


    "award": '//div[@class="ibt-table-row" and @aria-rowindex="1"]/div/div/div/a',

    "reset search": '//button[@class="reset-button"]',
    "Download button": '//*[contains(@class,"download-button ") and not(contains(@class, "disabled"))]',
    "Award button": '//button[@class="level-button" and @aria-label="Award"]',
    "Everything button": '//button[@class="level-button" and @aria-label="Everything"]',

    "Award button label": '//div[@class="subaward-toggle__label subaward-toggle__label_active"]',
    "sub awards button": '//*[@id="main-content"]/div/div[2]/div[3]/div/div/div[1]/div/button',
    "Visualization title": '//*[@id="results-section-table"]/div[1]/h2',
    "Submit Search": '//button[@class="submit-button"]',

    "Transactions button": '//button[@class="level-button" and @aria-label="Transaction"]',

    "keyword field": '//*[@id="search"]',
    "contracts tab": '//*[@id="results-section-table"]/div[2]/button[1]/div/div[2]',
    "grants tab": '//*[@id="results-section-table"]/div[2]/button[3]',

    "keyword contracts": '//div[@class="count-badge  active"]', #'//*[@id="results-section-table"]/div[2]/button[1]/div/div[2]',
    "keyword download button": '//*[contains(@class, "download-button")]',
    #advanced search tabs

    "Active row badge": '//div[@class="count-badge  active"]',
    "Map tab": tab("Map"),
    "Time tab": tab("Time"),
    "Categories tab": '//button[contains(@class, "visualization-type-tab") and @title = "Categories"]',
    "Table tab": tab("Table"),

    "Contracts search tab": '//*[@id="results-section-table"]/div[2]/button[1]',
    "Contract IDVs search tab": '//*[@id="results-section-table"]/div[2]/button[2]',
    "Grants search tab": '//*[@class="table-types"]//div[@class="tab-label" and text()="Grants"]',
    "Direct Payments search tab": '//*[@id="main-content"]/div/div[2]/div[3]/div[2]/div/div[2]/div/div/div[2]/button[4]',
    "Loans search tab": '//*[@id="results-section-table"]/div[2]/button[5]',
    "Other search tab": '//*[@id="main-content"]/div/div[2]/div[3]/div[2]/div/div[2]/div/div/div[2]/button[6]',

    "Sub-Contracts tab": '//*[@id="results-section-table"]/div[2]/button[1]',
    "Sub-Grants tab": '//*[@id="results-section-table"]/div[2]/*[contains(@title,"Sub-Grants")]',

    "Award ID input": '//*[@id="search"]',

    #Profiles
    "profile search field": '//*[@id="main-content"]/div/div[2]/form/input',
    "Treasury agency profile": '//*[@id="agency-overview"]/div[1]/div[2]/h3',
    "top agency name": '//*[@id="agency-landing-results"]/div/div/table/tbody/tr/td[1]/div/div/a',
    "top fed result": '//*[@id="account-landing-results"]/div/table/tbody/tr[1]/td[2]/div/div/a',

    #agency profiles
    "Overview": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[1]/a',
    "Obligated Amount": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[2]/a',
    "Object Classes": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[3]/a',
    "Federal Accounts": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[4]/a',
    "Agency Mission section": '//*[@id="agency-overview"]/div[2]',
    "Obligated Amount section": '//*[@id="agency-obligated-amount"]',
    "Object Classes section": '//*[@id="agency-object-classes"]',
    "Federal Accounts section": '//*[@id="agency-federal-accounts"]',

    #federal account profile
    "Account Description": '//*[@id="main-content"]/div[1]/div[1]/div[1]/h4',
    "Fiscal Year Summary": '//*[@id="main-content"]/div[1]/div[1]/div[2]/h4',
    "FY Snapshot": '//*[@id="main-content"]/div[1]/h3[2]',
    "Filter by:": '//*[@id="main-content"]/div[2]/div[1]/div[1]/h6',
    "Spending Over Time": '//*[@id="results-section-time"]',
    "Spending by Category": '//*[@id="results-section-rank"]',
    "Spending by Award": '//h2[@class="visualization-title"]',

    #state profile
    "state search": '//*[@id="main-content"]/div/div[2]/div[1]/form/input',
    "texas": '//*[@id="main-content"]/div/div[2]/div[3]/table/tbody/tr[2]/td[1]/a',
    "state header": '//*[@id="state-overview"]/div[1]/h2',
    "State Name Header": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[1]/div/div[1]/div',
    "State Amount Header": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[2]/div/div[1]/div',
    "State Percent Header": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[3]/div/div[1]/div',
    "State Table Value 1": '//*[@id="main-content"]/div/div[2]/div[3]/table/tbody/tr[1]/td[1]/a',
    "State Table Value 2": '//*[@id="main-content"]/div/div[2]/div[3]/table/tbody/tr[2]/td[1]/a',
    "State Name Sort Ascending": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[1]/div/div[2]/button[1]',
    "State Awarded Sort Ascending": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[2]/div/div[2]/button[1]',
    "State Percent Sort Ascending": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[3]/div/div[2]/button[1]',
    "State Name Sort Descending": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[1]/div/div[2]/button[2]',
    "State Awarded Sort Descending": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[2]/div/div[2]/button[2]',
    "State Percent Sort Descending": '//*[@id="main-content"]/div/div[2]/div[3]/table/thead/tr/th[3]/div/div[2]/button[2]',
    "State Page Header": '//*[@id="state-overview"]/div[1]/h2',
    "state picker": '//*[@id="main-content"]/div/div[1]/div/div[2]/div',
    "state test": '/html/body/div/div/div/main/div',
    "State Overview": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[1]/a',
    "State Transactions": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[2]/a',
    "State Top 5": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[3]/a',

    #recipients profile
    "recipients search": '//*[@id="main-content"]/div/div[2]/form/input',
    "Parent Recipient button": '//*[@id="recipient-labels__icon-parent"]/div', #'//*[@id="recipient-labels__icon-parent"]/div/button',
    "Parent Recipient tooltip": '//div[@class="homepage-hero-tooltip"]',
    "Child Recipient button": '//*[@id="recipient-labels__icon-child"]/div/button',
    "Child Recipient tooltip": '//div[@class="homepage-hero-tooltip"]',
    "Recipient button": '//*[@id="recipient-labels__icon-recipient"]/div/button',
    "Recipient tooltip": '//div[@class="homepage-hero-tooltip"]',

    # "All Awards tab": '//*[@id="main-content"]/div/div[3]/div[1]/div[3]/div[1]/button[1]',
    "All Awards tab": '//*[@class="table-types"]//div[@class="tab-label" and text()="All Awards"]',
    # "Contracts tab": '//*[@id="main-content"]/div/div[3]/div[1]/div[3]/div[1]/button[2]',
    "Contracts tab": '//*[@class="table-types"]//div[@class="tab-label" and text()="Contracts"]',
    # "Grants tab": '//*[@id="main-content"]/div/div[3]/div[1]/div[3]/div[1]/button[3]',
    "Grants tab": '//*[@class="table-types"]//div[@class="tab-label" and text()="Grants"]',
    # "Direct Payments tab": '//*[@id="main-content"]/div/div[3]/div[1]/div[3]/div[1]/button[4]',
    "Direct Payments tab": '//*[@class="table-types"]//div[@class="tab-label" and text()="Direct Payments"]',
    # "Loans tab": '//*[@id="main-content"]/div/div[3]/div[1]/div[3]/div[1]/button[5]',
    "Loans tab": '//*[@class="table-types"]//div[@class="tab-label" and text()="Loans"]',
    # "Other tab": '//*[@id="main-content"]/div/div[3]/div[1]/div[3]/div[1]/button[6]',
    "Other tab": '//*[@class="table-types"]//div[@class="tab-label" and text()="Other Financial Assistance"]',

    "recipient link": '//*[@id="main-content"]/div/div[4]/div/table/tbody/tr[1]/td[1]/a',
    "time dropdown": '//*[@id="main-content"]/div/div[1]/div/div[2]/div/div/div[2]/button/div[1]',
    "Transactions": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[2]/a',
    "Top 5": '//*[@id="main-content"]/div/div[1]/div/div[2]/ul/li[3]/a',

    "latest fiscal year": '//*[@id="main-content"]/div/div[1]/div/div[2]/div/div/div[2]/ul/li[7]/button',
    "Transactions Over Time": '//*[@id="recipient-transactions-over-time"]',
    "Top 5 section": '//*[@id="recipient-top-five"]',

    "Awarding Agencies top 5": '//*[@id="recipient-top-five"]/div[2]/div[1]/div[1]',
    "Awarding Sub-Agencies top 5": '//*[@id="recipient-top-five"]/div[2]/div[1]/div[2]',
    "Federal Accounts top 5": '//*[@id="recipient-top-five"]/div[2]/div[2]/div[1]',
    "CFDA Programs top 5": '//*[@id="recipient-top-five"]/div[2]/div[2]/div[2]',
    "NAICS Codes top 5": '//*[@id="recipient-top-five"]/div[2]/div[3]/div[1]',
    "Product Services Codes top 5": '//*[@id="recipient-top-five"]/div[2]/div[3]/div[2]',
    "Countries top 5": '//*[@id="recipient-top-five"]/div[2]/div[4]/div[1]',
    "U.S. States or Territories top 5": '//*[@id="recipient-top-five"]/div[2]/div[4]/div[2]',

    "View child recipients": '//*[@id="recipient-overview"]/div/div[1]/button',
    "Child recipients": '//*[@id="react-aria-modal-dialog"]/div',
    "list of child recipients": '//*[@id="react-aria-modal-dialog"]/div/div[2]/table/tbody',
    "Recipient Name": '//*[@id="react-aria-modal-dialog"]/div/div[2]/table/thead/tr/th[1]/div/div[1]/div',
    "DUNS": '//*[@id="react-aria-modal-dialog"]/div/div[2]/table/thead/tr/th[2]/div/div[1]/div',
    "State": '//*[@id="react-aria-modal-dialog"]/div/div[2]/table/thead/tr/th[3]/div/div[1]/div',
    "Transaction Amount": '//*[@id="react-aria-modal-dialog"]/div/div[2]/table/thead/tr/th[4]/div/div[1]/div',
    "Percent": '//*[@id="react-aria-modal-dialog"]/div/div[2]/table/thead/tr/th[5]/div/div[1]/div',
    "Sort table by descending awarded amount": '//*[@id="react-aria-modal-dialog"]/div/div[2]/table/thead/tr/th[4]/div/div[2]/button[2]',
    "Sort table by descending percent of total": '//*[@id="react-aria-modal-dialog"]/div/div[2]/table/thead/tr/th[5]/div/div[2]/button[2]',

    #Downloads

    #Award data archive
    "Agency dropdown": '//*[@id="main-content"]/div/div[2]/div/div[1]/form/div[1]/div/button',
    "Department of Education": '//*[@id="main-content"]/div/div[2]/div/div[1]/form/div[1]/div/div/ul/li[6]/button',
    "Fiscal year dropdown": '//*[@id="main-content"]/div/div[2]/div/div[1]/form/div[3]/div/button',
    "previous year": '//*[@id="main-content"]/div/div[2]/div/div[1]/form/div[3]/div/div/ul/li[2]/button',
    "Apply": '//*[@id="main-content"]/div/div[2]/div/div[1]/form/div[4]/input',
    "Agency column": '//*[@id="main-content"]/div/div[2]/div/div[2]/table/tbody/tr[1]/td[1]',
    "Fiscal year column": '//*[@id="main-content"]/div/div[2]/div/div[2]/table/tbody/tr[1]/td[3]',

    "first download link": '//*[@id="main-content"]/div/div[2]/div/div[2]/table/tbody/tr[1]/td[2]/a',
    "second download link": '//*[@id="main-content"]/div/div[2]/div/div[2]/table/tbody/tr[2]/td[2]/a',

    #custom award data
    "Prime Awards checkbox": '//*[@id="checkbox-123"]',
    "Contracts checkbox": '//input[@type="checkbox" and @value="contracts"]',
    "Agency select": '//button[@title="Select an Agency"]',
    "Department of Treasury": '//li/button[@title="Department of the Treasury"]',
    "current fiscal year": '//*[@id="main-content"]/div/div[2]/div/div[1]/form/div[6]/div/div[2]/div[1]/button[2]',
    'last 30 days': '//div[@class="time-period-buttons"]//button[text()="last 30 days"]',
    "the Download button": '//input[@type="submit"]',

    #custom account data
    "budget function": '//*[@id="main-content"]/div/div[2]/div/div[1]/form/div[1]/div/div[1]/div/div/button',
    "function": '//*[@id="main-content"]/div/div[2]/div/div[1]/form/div[1]/div/div[1]/div/div/div/ul/li[1]/button',
    "agency dropdown": '//button[@class="selected-button" and contains(@title, "Agency")]',
    "Federal Trade Commission": '//button[@class="item-button" and @title="Federal Trade Commission"]',

    #agency submission data
    "financial assistance files": '/html/body/div/p[1]/a',
    "quarterly act files": '/html/body/div/p[2]/a',

    #data dictionary
    "data dictionary table": '//*[@id="bottomBar"]',
    "data dictionary search": '//input[@class="dictionary-search__input"]',
    "data dictionary download": '//*[@id="main-content"]/div/div[2]/div/div[1]/div[2]/a',

    #database download
    "setup guide link": '/html/body/div/p[4]/a',
    "database download link": '//*[@id="database"]',

    #Time tab
    "Awards Switch": '//*[@id="main-content"]/div/div[2]/div[3]/div[2]/div/div[1]/div/button/*[local-name()="svg"]/*[local-name()="g"]/*[local-name()="g"]/*[local-name()="circle"]',
    "Bar Graph": '//*[@id="results-section-time"]',
    "Time Heading": '//*[@id="results-section-time"]/h2',
    "Bar": '//*[@id="results-section-time"]/div[2]/span/div/svg/g/g[3]',
    "Graph Y Axis": time_graph('/*[local-name()="g"]/*[local-name()="g" and @class="bar-axis"]'),
    "Graph X Axis": time_graph('/*[local-name()="g"]/*[local-name()="g" and @class="bar-axis"][2]'),
    "Time Circle": time_graph('/*[local-name()="g"]/*[local-name()="g"][4]/*[local-name()="g"]/*[local-name()="g"]/*[local-name()="text" and @class="key-label"]'),
    "Time Legend": time_graph('/*[local-name()="g"]/*[local-name()="g"][4]/*[local-name()="g"]/*[local-name()="g"]/*[local-name()="circle" and @fill="#708893"]'),
    "Result Bar": time_graph('/*[local-name()="g"]/*[local-name()="g"][3]/*[local-name()="g"]/*[local-name()="rect" and @class="bar-item" and @fill="#708893"]'),
    "Hover Box": time_graph('/*[local-name()="g"]/*[local-name()="g"][3]/*[local-name()="g"]/*[local-name()="rect" and @class="bar-item hover" and @fill="#708893"]'),
    "Years Option": '//*[@id="results-section-time"]/div[1]/div[2]/div/ul/li[1]/*[local-name()="button" and @class="period-button active"]',
    "Quarters Option": '//*[local-name()="button" and @value="quarter"]',
    "Months Option": '//*[local-name()="button" and @value="month"]',
    "Years Result": time_graph('/*[local-name()="g"]/*[local-name()="g"][3]/*[local-name()="g"]'),
    "Quarters Result": time_graph('/*[local-name()="g"]/*[local-name()="g"][3]/*[local-name()="g"][4]'),
    "Months Result": time_graph('/*[local-name()="g"]/*[local-name()="g"][3]/*[local-name()="g"][12]'),

    #Glossary
    "Actual glossary": '//*[@id="app"]/div/div/div[1]/div/span/div',
    "glossary term": '//*[@id="app"]/div/div/div[1]/div/span/div/aside/div[2]/div[1]/div/div/h2',
    "Glossary":'//*[@id="header-glossary-button"]',
    "Search for a term...":'//form/input[@class="search-field"]',
    "Award Amount":'//*[@class="glossary-link"]/span[1][text() = "Award Amount"]',
    "definition":'//div[@class="definition-wrapper"]',
    "Glossary Selected Item Title": '//*[@id="app"]/div[1]/div/div[1]/div/span/div/aside/div[2]/div[1]/div/div/h2',
    "Official Definition":'//button[contains(@class, "definition-tab") and text() = "Official Definition"]',
    "Official Def":'//div[@class = "definition-wrapper"]',
    "Plain Language":'//*[@id="app"]/div/div/div[1]/div/span/div/aside/div[2]/div[1]/div/ul/li[1]/button',
    "Back":'//*[@id="app"]/div/div/div[1]/div/span/div/aside/div[2]/div[1]/div/button/div/div',
    "X":'//*[@id="glossary-close-button"]',
    "Glossary pink button":'//*[@id="app"]/div/div/div[2]/div[1]/button',
    "Glossary Result 1": '//*[@id="app"]/div[1]/div/div[1]/div/span/div/aside/div[2]/div[1]/div/div[1]/ul/li/button',
    "Glossary See Also Result 1": '//*[@id="app"]/div[1]/div/div[1]/div/span/div/aside/div[2]/div[1]/div/div/div[2]/div/ul/li[1]/a',
    "Glossary See Also Result 2": '//*[@id="app"]/div/div/div[1]/div/span/div/aside/div[2]/div[1]/div/div/div[2]/div/p[2]/a',
    "Glossary No Results Title": '//*[@id="app"]/div[1]/div/div[1]/div/span/div/aside/div[2]/div[1]/div/h2',
    "ID header": '//*[@id="app"]/div[1]/div/div[2]/div/div/div/div[2]/div/ul/li[1]/div/div[2]',
    "description cell" : '//*[@id="main-content"]/div[2]/div[2]/div/table/tbody/tr[1]/td[2]',
    "top transaction description": '//*[@id="details-table-section"]/div[4]/div/div/div[2]/div/div/div/div[1]/div[5]/div/div',

    "contracts table headers":'//div[@class="header-label"]',
    "awarding agency label": '//*[@id="main-content"]/div[1]/div/div[1]/div/div[2]',
    "recipient label": '//*[@id="main-content"]/div[1]/div/div[3]/div',
    "Transaction History tab": '//*[@id="details-table-section"]/div[1]/button[1]',
    "Sub-Awards tab": '//*[@id="details-table-section"]/div[1]/button[2]',
    "Financial Details tab": '//*[@id="details-table-section"]/div[1]/button[3]',
    "Additional Details tab": '//*[@id="details-table-section"]/div[1]/button[4]',

    "Additional Details link": '//*[@id="main-content"]/div[2]/div[2]/button',
    "Awarding Agency cell": '//*[@id="details-table-section"]/div[4]/div/div[2]/div[2]/div[1]/div[2]',
    "Awarding Sub-agency cell": '//*[@id="details-table-section"]/div[4]/div/div[2]/div[2]/div[2]/div[2]',
    "Awarding office cell": '//*[@id="details-table-section"]/div[4]/div/div[2]/div[2]/div[3]/div[2]',
    "Funding agency cell": '//*[@id="details-table-section"]/div[4]/div/div[2]/div[2]/div[4]/div[2]',
    "Funding sub-agency cell": '//*[@id="details-table-section"]/div[4]/div/div[2]/div[2]/div[5]/div[2]',
    "Funding office cell": '//*[@id="details-table-section"]/div[4]/div/div[2]/div[2]/div[6]/div[2]',

    "Solicitation ID": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[1]/div[2]',
    "Solicitation procedures": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[2]/div[2]',
    "Offer recieved": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[3]/div[2]',
    "Extent completed": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[4]/div[2]',
    "Set-aside type": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[6]/div[2]',
    "Commercial Item Aquisition Procedures": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[7]/div[2]',
    "Commercial Item Test Program": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[8]/div[2]',
    "Evaluated Preference": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[9]/div[2]',
    "FedBizOps": '//*[@id="details-table-section"]/div[4]/div/div[3]/div[2]/div[10]/div[2]',
    "Product Service Code": '//*[@id="details-table-section"]/div[4]/div/div[4]/div[2]/div[1]/div[2]',
    "NAICS Code": '//*[@id="details-table-section"]/div[4]/div/div[4]/div[2]/div[2]/div[2]',
    "Clinger-Cohen Complient": '//*[@id="details-table-section"]/div[4]/div/div[5]/div[2]/div[1]/div[2]',
    "Labor Standards": '//*[@id="details-table-section"]/div[4]/div/div[5]/div[2]/div[3]/div[2]',
    "Subject to Materials": '//*[@id="details-table-section"]/div[4]/div/div[5]/div[2]/div[4]/div[2]',
    "Cost or Pricing Data": '//*[@id="details-table-section"]/div[4]/div/div[6]/div[2]/div[1]/div[2]',
    "Foreign Funding": '//*[@id="details-table-section"]/div[4]/div/div[6]/div[2]/div[1]/div[2]',
    "Interagency Contracting Authority": '//*[@id="details-table-section"]/div[4]/div/div[6]/div[2]/div[4]/div[2]',
    "Price Evaluation Adjustment Preference": '//*[@id="details-table-section"]/div[4]/div/div[6]/div[2]/div[6]/div[2]',
    "Subcontracting Plan": '//*[@id="details-table-section"]/div[4]/div/div[6]/div[2]/div[8]/div[2]',
    "Multi Year Contract": '//*[@id="details-table-section"]/div[4]/div/div[6]/div[2]/div[9]/div[2]',
    "Purchase Card as Payment Method": '//*[@id="details-table-section"]/div[4]/div/div[6]/div[2]/div[10]/div[2]',
    "Consolidated Contract": '//*[@id="details-table-section"]/div[4]/div/div[6]/div[2]/div[11]/div[2]' ,
    "Officer 1": '//*[@id="details-table-section"]/div[4]/div/div[7]/div[2]/div[1]/div[2]',
    "Officer 2": '//*[@id="details-table-section"]/div[4]/div/div[7]/div[2]/div[2]/div[2]',
    "Officer 3": '//*[@id="details-table-section"]/div[4]/div/div[7]/div[2]/div[3]/div[2]',
    "Officer 4": '//*[@id="details-table-section"]/div[4]/div/div[7]/div[2]/div[4]/div[2]',
    "Officer 5": '//*[@id="details-table-section"]/div[4]/div/div[7]/div[2]/div[5]/div[2]',

    "Raw files header": '/html/body/div/h1',

    "accessibility link": '//footer//a[text() = "Accessibility"]',
    "privacy policy link": '//footer//a[text() = "Privacy Policy"]',
    "FOIA link": '//footer//a[text() = "Freedom of Information Act"]',
    "about section title": '//*[@id="main-content"]/div/div[2]/div/div/h2',
    "about link": '//footer/div[1]/div[2]/div[1]/ul/li/a',
    "FAQs link": '//footer/div[1]/div[2]/div[2]/ul/li[1]/a',
    "DAIMS page header": '//*[@id="main"]/section[1]/content-lock/h-box[2]/v-box/h1',
    "footer logo": '//footer/div[1]/div[1]/a',
    "Contact us link": '//footer/div[1]/div[2]/div[2]/ul/li[3]/a',
    "data model link": '//footer/div[1]/div[2]/div[3]/ul/li[1]/a',
    "data lab link": '//footer/div[1]/div[2]/div[3]/ul/li[2]/a',
    "data lab header": '//*[@id="banner"]/p[1]',
    "api link": '//footer/div[1]/div[2]/div[4]/ul/li[1]/a',
    "Explore the code link": '//footer/div[1]/div[2]/div[4]/ul/li[2]/a',
    "API header": '/html/body/div[2]/div/div/div/div/div[2]/section/h1',
    "Accessibility sidebar link": '//div[@class="about-sidebar"]//a[text() = "Accessibility"]',
    "Privacy sidebar link": '//div[@class="about-sidebar"]//a[text() = "Privacy Policy"]',
    "FOIA sidebar link": '//div[@class="about-sidebar"]//a[text() = "Freedom of Information Act"]',


    "Table error message": '//*[@id="results-section-table"]/div[3]/span/div/div/div[2]',

    "spending feature load message": '//*[@id="main-content"]/div/div/div[2]/div/div/div[2]',

    "Keyword filter tooltip": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[1]/div/div',
    "Keyword filter info": '//*[@id="accessory-view"]',

    "Country dropdown": '//*[@id="country-button"]',
    "United states": '//*[@id="geo-dropdown-country"]/li[1]/button',
    "All Foreign Countries": '//*[@id="geo-dropdown-country"]/li[2]/button',
    "Andorra": '//*[@id="geo-dropdown-country"]/li[8]/button',
    "State dropdown": '//*[@id="state-button"]',
    "All states": '//*[@id="geo-dropdown-state"]/li[1]/button',
    "Colorado": '//*[@id="geo-dropdown-state"]/li[7]/button',
    "County dropdown": '//*[@id="county-button"]',
    "All counties": '//*[@id="geo-dropdown-county"]/li[1]/button',
    "Cheyenne County": '//*[@id="geo-dropdown-county"]/li[11]/button',
    "District dropdown": '//*[@id="district-button"]',
    "All districts": '//*[@id="geo-dropdown-district"]/li[1]/button',
    "CO-01": '//*[@id="geo-dropdown-district"]/li[2]/button',
    "Place of performance tab": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[5]/div[2]/ul/li[1]/button',
    "Recipient location tab": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[5]/div[2]/ul/li[2]/button',
    "location warning": '//div[@class="geo-warning"]',
    "Add filter button": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[5]/div[2]/div[2]/div[1]/form[1]/button',
    "Location filter": '//*[@id="award-search-selected-locations"]/button',
    "zip code input": '//*[@id="location-picker-zip"]',
    "zip search button": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[5]/div[2]/div[2]/div[1]/form[2]/div/div/button',
    "zip result": '//*[@id="award-search-selected-locations"]/button',
    "invalid zip error": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[5]/div[2]/div[2]/div[1]/form[2]/div/div[2]',

    "Recipient Input": '//*[@id="search"]',
    "Recipient Search": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[6]/div[2]/div/div[1]/form/div/button',
    "Recipient Result": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[6]/div[2]/div/div[2]/button',
    "DUNS Link": '//*[@id="results-section-table"]/div[3]/div[2]/div/div[2]/div/div/div/div[1]/div',
    "DUNS Result": '//*[@id="main-content"]/div[1]/div/div[3]/ul/li[2]/div/div[2]',
    "DUNS Parent Result": '//*[@id="main-content"]/div[1]/div/div[3]/ul/li[3]/div/div[2]',

    "Business checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/div/div/div/label/input',
    "Business toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/div/div/div/button',

    "Small business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[1]/label/input',
    "Other than small business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[2]/label/input',
    "Corporate tax exempt": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[3]/label/input',
    "Corporate not tax exempt": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[4]/label/input',
    "Partnership": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[5]/label/input',
    "Sole proprietorship": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[6]/label/input',
    "Manufacturer": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[7]/label/input',
    "Sub-chapter": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[8]/label/input',
    "LLC": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[1]/ul/li[9]/label/input',

    "Minority owned business checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/div/div/div/label/input',
    "Minority owned business toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/div/div/div/button',
    "Alaskan Native": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[1]/label/input',
    "American Indian": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[2]/label/input',
    "Asian Pacific": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[3]/label/input',
    "Black": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[4]/label/input',
    "Hispanic": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[5]/label/input',
    "Native American": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[6]/label/input',
    "Native Hawaiian": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[7]/label/input',
    "Subcontinent Asian Indian": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[8]/label/input',
    "Tribally Owned": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[9]/label/input',
    "Other Minority": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[2]/ul/li[10]/label/input',

    "Women owned business checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[3]/div/div/div/label/input',
    "Women owned business toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[3]/div/div/div/button',
    "Women owned small business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[3]/ul/li[1]/label/input',
    "Economically disadvantages": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[3]/ul/li[2]/label/input',
    "Joint venture": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[3]/ul/li[3]/label/input',
    "Joint venture disadvantaged": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[3]/ul/li[4]/label/input',

    "Veteran owned business checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[4]/div/div/div/label/input',
    "Veteran owned business toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[4]/div/div/div/button',
    "Service disabled veteran owned": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[4]/ul/li/label/input',

    "Special designation checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/div/div/div/label/input',
    "Special designation toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/div/div/div/button',
    "8a": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[1]/label/input',
    "Ability One": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[2]/label/input',
    "DoT Certified": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[3]/label/input',
    "Emerging Small Business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[4]/label/input',
    "Federally Funded R&D": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[5]/label/input',
    "HUBZone Firm": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[6]/label/input',
    "Labor Surplus Firm": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[7]/label/input',
    "SBA 8a": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[8]/label/input',
    "Self-Certified Small Business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[9]/label/input',
    "Small Agricultural Coop": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[10]/label/input',
    "Small Disadvantaged Business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[11]/label/input',
    "Community Developed": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[12]/label/input',
    "US Owned Business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[13]/label/input',
    "Foreign-Owned US Business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[14]/label/input',
    "Foreign-Owned & Located Business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[15]/label/input',
    "Foreign Government": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[16]/label/input',
    "International Organization": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[17]/label/input',
    "Domestic Shelter": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[18]/label/input',
    "Hospital": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[19]/label/input',
    "Veterinary Hospital": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[5]/ul/li[20]/label/input',

    "Nonprofit checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[6]/div/div/div/label/input',
    "Nonprofit toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[6]/div/div/div/button',
    "Foundation": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[6]/ul/li[1]/label/input',
    "Community Development Corporations": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[6]/ul/li[2]/label/input',

    "Higher Education checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[7]/div/div/div/label/input',
    "Higher Education toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[7]/div/div/div/button',
    "Public Institution": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[7]/ul/li[1]/label/input',
    "Private Institution": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[7]/ul/li[2]/label/input',
    "Minority-Serving": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[7]/ul/li[3]/label/input',
    "School of Forestry": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[7]/ul/li[4]/label/input',
    "Veterinary College": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[7]/ul/li[5]/label/input',

    "Government checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/div/div/div/label/input',
    "Government toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/div/div/div/button',
    "National Government": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[1]/label/input',
    "Interstate Entity": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[2]/label/input',
    "Regional and State": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[3]/label/input',
    "Regional Organization": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[4]/label/input',
    "US Territory": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[5]/label/input',
    "Council of Government": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[6]/label/input',
    "Local Government": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[7]/label/input',
    "Indian Native American Tribal Government": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[8]/label/input',
    "Authorities and Commissions": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[8]/ul/li[9]/label/input',


    "Individuals checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[7]/div[2]/div/ul/li[9]/div/div/div/label/input',

    "Table error message": '//*[@id="results-section-table"]/div[3]/span/div/div/div[2]',

    "spending feature load message": '//*[@id="main-content"]/div/div/div[2]/div/div/div[2]',

    "Under $1m checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/li[1]/div/div/div/label/input',
    "$1m-$25m checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/li[2]/div/div/div/label/input',
    "$25m-$100m checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/li[3]/div/div/div/label/input',
    "$100m-$500m checkbox": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/li[4]/div/div/div/label/input',
    "$500m & Above": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/li[5]/div/div/div/label/input',

    "min amount input": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/div/div[2]/input[1]',
    "max amount input": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/div/div[2]/input[2]',
    "amount search": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/div/div[2]/button',
    "Table error message": '//*[@id="results-section-table"]/div[3]/span/div/div/div[2]',

    "spending feature load message": '//*[@id="main-content"]/div/div/div[2]/div/div/div[2]',

    "amount checkbox label": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[8]/div[2]/div/ul/div/div[1]/li/div/label',
    "amount checkbox": '//*[@id="award-amount-specific"]',

    "Combination": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[1]/div/div/div/label/input',
    "Cost No Fee": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[2]/div/div/div/label/input',
    "Cost Plus Award Fee": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[3]/div/div/div/label/input',
    "Cost Plus Fixed Fee": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[4]/div/div/div/label/input',
    "Cost Plus Incentive Fee": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[5]/div/div/div/label/input',
    "Cost Sharing": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[6]/div/div/div/label/input',
    "Firm Fixed Price": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[7]/div/div/div/label/input',
    "Fixed Price Award Fee": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[8]/div/div/div/label/input',
    "Fixed Price Incentive": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[9]/div/div/div/label/input',
    "Fixed Price Level of Effort": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[10]/div/div/div/label/input',
    "Fixed Price Redetermination": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[11]/div/div/div/label/input',
    "Fixed Price with Economic Price Adjustment": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[12]/div/div/div/label/input',
    "Labor Hours": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[13]/div/div/div/label/input',
    "Order Department": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[14]/div/div/div/label/input',
    "Other": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[15]/div/div/div/label/input',
    "Time and Materials": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[2]/div/ul/li[16]/div/div/div/label/input',
    "See more toggle": '//button[@class="see-more contract-filter-toggle-button"]',

    "Contract pricing toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[13]/div[1]/button',

    "Set aside see more toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/button',
    "8a sole source": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[1]/div/div/div/label/input',
    "8a HUBZone": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[2]/div/div/div/label/input',
    "8a Competed": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[3]/div/div/div/label/input',
    "Buy Indian": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[4]/div/div/div/label/input',
    "Combination HUBZONE 8a": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[5]/div/div/div/label/input',
    "Econ-disadvantaged women-owned small": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[6]/div/div/div/label/input',
    "Emerging small business set aside": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[7]/div/div/div/label/input',
    "HBCU or MI Partial": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[8]/div/div/div/label/input',
    "HBCU or MI Total": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[9]/div/div/div/label/input',
    "HUBZone Set aside": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[10]/div/div/div/label/input',
    "HUBZone Sole Source": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[11]/div/div/div/label/input',
    "Indian Economic Enterprise": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[12]/div/div/div/label/input',
    "Indian Small Business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[13]/div/div/div/label/input',
    "No Set Aside Used": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[14]/div/div/div/label/input',
    "Reserved for small business": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[15]/div/div/div/label/input',
    "SDB Set-Aside": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[16]/div/div/div/label/input',
    "SDVOSB Sole Source": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[17]/div/div/div/label/input',
    "Service-Disabled Veteran Set Aside": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[18]/div/div/div/label/input',
    "Small Business Set-Aside Partial": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[19]/div/div/div/label/input',
    "Small Business Set-Aside Total": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[20]/div/div/div/label/input',
    "Very Small Business Set-Aside": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[21]/div/div/div/label/input',
    "Veteran Set-Aside": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[22]/div/div/div/label/input',
    "Veteran Sole Source": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[23]/div/div/div/label/input',
    "Women-Owned small business set aside": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div[2]/div/ul/li[24]/div/div/div/label/input',

    "Set aside toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[14]/div/button',

    "extent competed see more toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/button',
    "Extent competed filter toggle": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[1]/button',

    "Competed under SAP": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[1]/div/div/div/label/input',
    "Competitive Delivery Order": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[2]/div/div/div/label/input',
    "Follow On to Competed Action": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[3]/div/div/div/label/input',
    "Full and Open Competition": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[4]/div/div/div/label/input',
    "Full and Open Competition after exclusion": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[5]/div/div/div/label/input',
    "Non-Competitive Delivery Order": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[6]/div/div/div/label/input',
    "Not Available for Competition": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[7]/div/div/div/label/input',
    "Not Competed": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[8]/div/div/div/label/input',
    "Not Competed under SAP": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[15]/div[2]/div/ul/li[9]/div/div/div/label/input',
    "table load message": '//div[@class="results-table-message-container"]',

    "category description": '//*[@id="results-section-rank"]/div[2]/div[1]/div[1]',
    "visualization tooltip": '//*[@class="visualization-tooltip"]',

    "tooltip title": '//*[@class="tooltip-title"]',
    "tooltip body": '//*[@class="tooltip-value]',
    "category chart hitzone":'//*[@class="chart-bar-hitzone"]',
    "Agencies graph tab": '//*[@id="results-section-rank"]/div[2]/div[1]/div[2]/button[1]',
    "Sub-agencies graph tab": '//*[@id="results-section-rank"]/div[2]/div[1]/div[2]/button[2]',
    "Graph label": '//g[transform="translate(0,0)"]/title',
    "Awarding agency drop": '//*[@id="results-section-rank"]/div[1]/div/div/ul/li[1]/button',
    "recipient drop": '//*[@id="results-section-rank"]/div[1]/div/div/ul/li[2]/button',
    "CFDA program drop": '//*[@id="results-section-rank"]/div[1]/div/div/ul/li[3]/button',
    "Industry code drop": '//*[@id="results-section-rank"]/div[1]/div/div/ul/li[4]/button',
    "visualization legend": '//*[@id="results-section-rank"]/div[2]/section/div[2]',
    "Category field picker": '//*[@id="results-section-rank"]/div[1]/div',
    "Show next ten button": '//*[@id="results-section-rank"]/div[2]/div[2]/button[2]',
    "Category load message": '//*[@id="results-section-rank"]/div[2]/section/div',
    "Agency Autocomplete Option 1": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[4]/div[2]/div[1]/div[1]/div/ul/li[1]',
    "Agency Autocomplete Option 2": '//*[@id="main-content"]/div/div[1]/div/div[3]/div[4]/div[2]/div[1]/div[1]/div/ul/li[2]',

    "PSC button": '//*[@id="results-section-rank"]/div[2]/div[1]/div[2]/button[1]',
    "NAICS button": '//*[@id="results-section-rank"]/div[2]/div[1]/div[2]/button[2]',

    "categories x axis": '//*[local-name()="svg" and @class="rank-graph"]/*[local-name()="g" and @class="bar-axis"]',
    "categories y axis": '//*[local-name()="svg" and @class="rank-graph"]/*[local-name()="g" and @class="bar-axis"]',

    "bar 1": '//*[local-name()="g" and @class="chart-bar-group"][1]',
    "bar 2": '//*[local-name()="g" and @class="chart-bar-group"][2]',
    "bar 3": '//*[local-name()="g" and @class="chart-bar-group"][3]',
    "bar 4": '//*[local-name()="g" and @class="chart-bar-group"][4]',
    "bar 5": '//*[local-name()="g" and @class="chart-bar-group"][5]',
    "bar 6": '//*[local-name()="g" and @class="chart-bar-group"][6]',
    "bar 7": '//*[local-name()="g" and @class="chart-bar-group"][7]',
    "bar 8": '//*[local-name()="g" and @class="chart-bar-group"][8]',
    "bar 9": '//*[local-name()="g" and @class="chart-bar-group"][9]',
    "bar 10": '//*[local-name()="g" and @class="chart-bar-group"][10]',
}

TIMING_DICT = {
    #buttons

    "Submit Search button": 0,
    "Try our Spending Explorer": 0,

    #Nav
    "Award Search top nav": 0,
    "Advanced Search": 0,

    #fy
    "2018 fy checkbox": 0,

    #filters

    "Location filter":0,
    "Agency filter":0,
    "Time Period filter":0,

    "shown filter button": 0,
    "Active filter label": 0,
    "filter group 1 title": 0,
    "filter item 1": 0,

    "Date range": 0,
    "start date input": 0,
    "start date icon": 0,

    "calendar previous": 0,
    "calendar 2 previous": 0,
    "calendar next": 0,
    "calendar day 1": 0,
    "end date input": 0,
    "end date icon": 0,
    "date submit": 0,
    "calendar today":0,
    "calendar today selected": 0,
    "date error message": 0,
    "calendar body": 0,


    "Contracts check": 0,
    "Contract toggle": 0,
    "BPAs": 0,
    "Purchase orders": 0,
    "Delivery orders": 0,
    "Definitive contracts": 0,

    "Contract IDVs checkbox": 0,
    "Contract IDVs toggle": 0,
    "GWAC": 0,
    "IDC multi agency contract": 0,
    "IDC requirements": 0,
    "IDC indefinite quantity": 0,
    "IDC definite quantity": 0,
    "FSS": 0,
    "BOA": 0,
    "BPA IDVs": 0,


    "Grants checkbox": 0,
    "Grants toggle": 0,
    "Block grant": 0,
    "Formula grant": 0,
    "Project grant": 0,
    "Cooperative agreement": 0,

    "Direct Payments checkbox": 0,
    "Direct Payments toggle": 0,
    "Direct Payment unrestricted use": 0,
    "Direct Payment specified use": 0,

    "Loans checkbox": 0,
    "Loans toggle": 0,
    "Direct loans": 0,
    "Guaranteed/Insured loans": 0,

    "Other checkbox": 0,
    "Other toggle": 0,
    "Insurance": 0,
    "Other financial assistance": 0,

    #inputs:
    "Zip Code": 0,
    "Awarding Agency": 5,

    #outputs
    "Search Results for contracts":0,
    "Top Banner": 0,

    "three pane": 0,
    "arrow": 1,
    "Spending explorer content": 0,
    "homepage dropdown": 0,
    "Awards content": 0,
    "advanced screenshot": 0,
    "keyword screenshot": 0,
    "advanced search option": 0,
    "keyword search option": 0,

    "Award Data Archive": 0,
    "Custom Award Data": 0,
    "Custom Account Data": 0,
    "Agency Submission Files": 0,
    "Database Download": 0,
    "API": 0,
    "Join the conversation": 0,

    "Visit our community page button": 5,
    "community header": 0,
    "community footer": 0,
    "community navigation": 0,

    #spending explorer
    "spending explorer header": 0,
    "spending feature box 2": 0,
    "spending feature box": 0,
    "spending table icon": 0,
    "spending table link": 0,
    "Start over": 0,

    "spending explorer fy drop": 0,
    "spending explorer fy": 0,
    "spending explorer quarter": 0,
    "spending explorer load message": 0,

    "budget glossary": 1,
    "agency glossary": 1,
    "object glossary": 1,

    "budget start": 0,
    "agency start": 0,
    "object start": 0,

    "view dropdown": 0,
    "budget drop": 1,
    "agency drop": 1,
    "object drop": 1,

    "Contracts search tab": 0,
    "Contract IDVs search tab": 0,
    "Grants search tab": 2,
    "Direct Payments search tab": 0,
    "Loans search tab": 0,
    "Other search tab": 0,
    "Sub-Contracts tab": 0,
    "Sub-Grants tab": 0,

    "award": 5,
    "reset search": 0,
    "Download button": 5,
    "Award button": 0,
    "Everything button": 0,
    "Transactions button": 0,
    "keyword field": 0,
    "contracts tab": 1,
    "grants tab": 1,

    "Award button label": 0,
    "sub awards button": 2,
    "Visualization title": 0,
    "Submit Search": 2,

    "Zip Code": 0,
    # "Awarding Agency": 0,
    "Recipient input": 0,
    "Keyword input": 0,
    "Award ID input": 0,
    "Funding Agency": 5,
    "CFDA": 5,
    "NAICS": 5,
    "PSC": 5,
    "TAS": 5,

    "CFDA filter": 0,
    "PSC filter": 0,

    "shown filter button": 0,

    "keyword contracts": 0,
    "keyword download button": 5,

    "Map tab": 5,
    "Time tab": 2,
    "Categories tab": 5,
    "Table tab": 2,
    "Contract IDVs tab": 1,
    "Award ID input":0,

    "ID header": 0,

    #Profiles
    "profile search field": 1,
    "Treasury agency profile": 3,
    "top agency name": 3,
    "top fed result": 3,

    #agency profile
    "Overview": 0,
    "Obligated Amount": 0,
    "Object Classes": 0,
    "Federal Accounts": 0,
    "Agency Mission section": 0,
    "Obligated Amount section": 0,
    "Object Classes section": 0,
    "Federal Accounts section": 0,

    #Federal account profile
    "Account Description": 0,
    "Fiscal Year Summary": 0,
    "FY Snapshot": 0,
    "Filter by:": 0,
    "Spending Over Time": 0,
    "Spending by Category": 0,
    "Spending by Award": 0,

    #state profile
    "state search": 0,
    "texas": 5,
    "state header": 0,

    #recipient profiles
    "Parent Recipient button": 0,
    "Parent Recipient tooltip": 0,
    "Child Recipient button": 0,
    "Child Recipient tooltip": 0,
    "Recipient button": 0,
    "Recipient tooltip": 0,
    "All Awards tab": 0,
    "Contracts tab": 0,
    "Grants tab": 0,
    "Direct Payments tab": 0,
    "Loans tab": 0,
    "Other tab": 0,

    "recipient link": 2,
    "time dropdown": 0,
    "latest fiscal year": 5,
    "Top 5": 0,
    "Transactions": 0,
    "Top 5 section": 0,

    "Transactions Over Time": 0,
    "Awarding Agencies top 5": 0,
    "Awarding Sub-Agencies top 5": 0,
    "Federal Accounts top 5": 0,
    "CFDA Programs top 5": 0,
    "NAICS Codes top 5": 0,
    "Product Services Codes top 5": 0,
    "Countries top 5": 0,
    "U.S. States or Territories top 5": 0,

    "View child recipients": 0,
    "Child recipients": 0,
    "list of child recipients": 0,
    "Recipient Name": 0,
    "DUNS": 0,
    "State": 0,
    "Transaction Amount": 0,
    "Percent": 0,
    "Sort table by descending awarded amount": 0,
    "Sort table by descending percent of total": 0,

    #Time tabs
    "Years Option": 1,
    "Quarters Option": 1,
    "Months Option": 1,
    "Years Result": 1,
    "Quarters Result": 1,
    "Months Result": 1,

    #Downloads

    #award data archive
    "Agency dropdown": 3,
    "Department of Education": 3,
    "Fiscal year dropdown": 3,
    "previous year": 3,
    "Apply": 5,
    "Agency column": 3,
    "Fiscal year column": 3,

    "first download link": 1,
    "second download link": 1,

    #custom award data
    "Prime Awards checkbox": 1,
    "Contracts checkbox": 1,
    "Agency select": 2,
    "Department of Treasury": 2,
    "current fiscal year": 2,
    'last 30 days': 2,
    "the Download button": 2,

    #custom account data
    "budget function": 2,
    "function": 2,
    "agency dropdown": 2,
    "Federal Trade Commission": 2,

    #agency submission data
    "financial assistance files": 0,
    "quarterly act files": 0,

    #data dictionary
    "data dictionary table": 0,
    "data dictionary search": 0,
    "data dictionary download": 0,

    #database download
    "setup guide link": 5,
    "database download link": 0,

    #Glossary
    "Actual glossary": 1,
    "glossary button": 1,
    "glossary term": 0,
    "Glossary": 3,
    "Award Amount": 2,
    "Search for a term...": 2,
    "Glossary Search Results": 2,
    "definition": 2,
    "Official Definition": 2,
    "Back": 2,
    "X": 3,
    "Glossary pink button": 5,

    "ID header": 0,
    "description cell": 0,
    "top transaction description": 0,
    "contracts table headers": 0,
    "awarding agency label": 0,
    "recipient label":0,

    "Transaction History tab": 0,
    "Sub-Awards tab": 0,
    "Financial Details tab": 0,
    "Additional Details tab": 0,

    "Additional Details link": 0,

    "Awarding Agency cell": 0,
    "Awarding Sub-agency cell": 0,
    "Awarding office cell": 0,
    "Funding agency cell": 0,
    "Funding sub-agency cell": 0,
    "Funding office cell": 0,

    "Solicitation ID": 0,
    "Solicitation procedures": 0,
    "Offer recieved": 0,
    "Extent completed": 0,
    "Set-aside type": 0,
    "Commercial Item Aquisition Procedures": 0,
    "Commercial Item Test Program": 0,
    "Evaluated Preference": 0,
    "FedBizOps": 0,
    "Product Service Code": 0,
    "NAICS Code": 0,
    "Clinger-Cohen Complient": 0,
    "Labor Standards": 0,
    "Subject to Materials": 0,
    "Cost or Pricing Data": 0,
    "Foreign Funding": 0,
    "Interagency Contracting Authority": 0,
    "Price Evaluation Adjustment Preference": 0,
    "Subcontracting Plan": 0,
    "Multi Year Contract": 0,
    "Purchase Card as Payment Method": 0,
    "Consolidated Contract": 0,
    "Officer 1": 0,
    "Officer 2": 0,
    "Officer 3": 0,
    "Officer 4": 0,
    "Officer 5": 0,

    "Raw files header":0,

    "accessibility link": 3,
    "privacy policy link": 3,
    "FOIA link": 3,
    "about section title": 0,
    "about link": 3,
    "FAQs link": 3,
    "footer logo": 3,
    "Contact us link": 3,
    "data model link": 3,
    "data lab link": 3,
    "api link": 3,
    "Explore the code link": 3,
    "Accessibility sidebar link": 3,
    "Privacy sidebar link": 3,
    "FOIA sidebar link": 3,
    "Recipient filter": 0,
    "Recipient input": 0,
    "Table error message":0,

    "Keyword filter tooltip": 0,
    "Keyword filter info": 0,

    "Country dropdown": 0,
    "United states": 0,
    "Andorra": 0,
    "State dropdown": 0,
    "All states": 0,
    "Colorado": 0,
    "County dropdown": 0,
    "Cheyenne County": 0,
    "All counties": 0,
    "District dropdown": 0,
    "All districts": 0,
    "CO-01": 0,
    "Place of performance tab": 0,
    "Recipient location tab": 0,
    "Add filter button": 0,
    "Location filter": 0,
    "zip code input": 0,
    "zip search button": 0,

    "Business checkbox": 0,
    "Business toggle": 0,
    "Small business": 0,
    "Other than small business": 0,
    "Corporate tax exempt": 0,
    "Corporate not tax exempt": 0,
    "Partnership": 0,
    "Sole proprietorship": 0,
    "Manufacturer": 0,
    "Sub-chapter": 0,
    "LLC": 0,

    "Minority owned business checkbox": 0,
    "Minority owned business toggle": 0,
    "Alaskan Native": 0,
    "American Indian": 0,
    "Asian Pacific": 0,
    "Black": 0,
    "Hispanic": 0,
    "Native American": 0,
    "Native Hawaiian": 0,
    "Subcontinent Asian Indian": 0,
    "Tribally Owned": 0,
    "Other Minority": 0,

    "Women owned business checkbox": 0,
    "Women owned business toggle": 0,
    "Women owned small business": 0,
    "Economically disadvantages": 0,
    "Joint venture": 0,
    "Joint venture disadvantaged": 0,

    "Veteran owned business checkbox": 0,
    "Veteran owned business toggle": 0,
    "Service disabled veteran owned": 0,

    "Special designation checkbox": 0,
    "Special designation toggle": 0,
    "8a": 0,
    "Ability One": 0,
    "DoT Certified": 0,
    "Emerging Small Business": 0,
    "Federally Funded R&D": 0,
    "HUBZone Firm": 0,
    "Labor Surplus Firm": 0,
    "SBA 8a": 0,
    "Self-Certified Small Business": 0,
    "Small Agricultural Coop": 0,
    "Small Disadvantaged Business": 0,
    "Community Developed": 0,
    "US Owned Business": 0,
    "Foreign-Owned US Business": 0,
    "Foreign-Owned & Located Business": 0,
    "Foreign Government": 0,
    "International Organization": 0,
    "Domestic Shelter": 0,
    "Hospital": 0,
    "Veterinary Hospital": 0,

    "Nonprofit checkbox": 0,
    "Nonprofit toggle": 0,
    "Foundation": 0,
    "Community Development Corporations": 0,

    "Higher Education checkbox": 0,
    "Higher Education toggle": 0,
    "Public Institution": 0,
    "Private Institution": 0,
    "Minority-Serving": 0,
    "School of Forestry": 0,
    "Veterinary College": 0,


    "Government checkbox": 0,
    "Government toggle": 0,
    "National Government": 0,
    "Interstate Entity": 0,
    "Regional and State": 0,
    "Regional Organization": 0,
    "US Territory": 0,
    "Council of Government": 0,
    "Local Government": 0,
    "Indian Native American Tribal Government": 0,
    "Authorities and Commissions": 0,

    "Individuals checkbox": 0,

    "spending feature load message": 0,


    "Under $1m checkbox": 0,
    "$1m-$25m checkbox": 0,
    "$25m-$100m checkbox": 0,
    "$100m-$500m checkbox": 0,
    "$500m & Above": 0,

    "min amount input": 0,
    "max amount input": 0,
    "amount search": 0,
    "spending feature load message": 0,

    "amount checkbox label": 0,
    "amount checkbox": 0,

    "Combination": 0,
    "Cost No Fee": 0,
    "Cost Plus Award Fee": 0,
    "Cost Plus Fixed Fee": 0,
    "Cost Plus Incentive Fee": 0,
    "Cost Sharing": 0,
    "Firm Fixed Price": 0,
    "Fixed Price Award Fee": 0,
    "Fixed Price Incentive": 0,
    "Fixed Price Level of Effort": 0,
    "Fixed Price Redetermination": 0,
    "Fixed Price with Economic Price Adjustment": 0,
    "Labor Hours": 0,
    "Order Department": 0,
    "Other": 0,
    "Time and Materials": 0,
    "See more toggle": 0,

    "Contract pricing toggle": 0,

    "Set aside see more toggle": 0,
    "8a sole source": 0,
    "8a HUBZone": 0,
    "8a Competed": 0,
    "Buy Indian": 0,
    "Combination HUBZONE 8a": 0,
    "Econ-disadvantaged women-owned small": 0,
    "Emerging small business set aside": 0,
    "HBCU or MI Partial": 0,
    "HBCU or MI Total": 0,
    "HUBZone Set aside": 0,
    "HUBZone Sole Source": 0,
    "Indian Economic Enterprise": 0,
    "Indian Small Business": 0,
    "No Set Aside Used": 0,
    "Reserved for small business": 0,
    "SDB Set-Aside": 0,
    "SDVOSB Sole Source": 0,
    "Service-Disabled Veteran Set Aside": 0,
    "Small Business Set-Aside Partial": 0,
    "Small Business Set-Aside Total": 0,
    "Very Small Business Set-Aside": 0,
    "Veteran Set-Aside": 0,
    "Veteran Sole Source": 0,
    "Women-Owned small business set aside": 0,

    "Set aside toggle": 0,

    "extent competed see more toggle": 0,
    "Extent competed filter toggle": 0,

    "Competed under SAP": 0,
    "Competitive Delivery Order": 0,
    "Follow On to Competed Action": 0,
    "Full and Open Competition": 0,
    "Full and Open Competition after exclusion": 0,
    "Non-Competitive Delivery Order": 0,
    "Not Available for Competition": 0,
    "Not Competed": 0,
    "Not Competed under SAP": 0,

    "table load message": 0,

    "category description": 0,
    "visualization tooltip": 0,
    "tooltip title": 0,
    "tooltip body": 0,
    "category chart hitzone": 0,
    "Agencies graph tab": 0,
    "Sub-agencies graph tab ": 0,
    "Graph label": 0,
    "Awarding agency drop": 3,
    "recipient drop": 3,
    "CFDA program drop": 3,
    "Industry code drop": 3,
    "visualization legend": 0,
    "Show next ten button": 2,
    "Category load message": 0,

    "PSC button": 0,
    "NAICS button": 0,
}
