/**
 * buildNginxRedirects.js
 *
 * Drop-in replacement for buildRedirectConfig.js — instead of writing
 * redirect-config.json for CloudFront, writes an nginx-ready redirects.conf.
 *
 * Usage:
 *   node buildNginxRedirects.js
 *   node buildNginxRedirects.js --agency-file ./path/to/agencyIdsToSlugs.js --output ./redirects.conf
 *
 * Then in nginx.conf inside your server {} block:
 *   include /etc/nginx/redirects.conf;
 */

import fs from 'fs';
import path from 'path';
import { parseArgs } from 'util';
import { URLifyStateName } from '../src/js/features/state/stateHelper.js';
import agencyIdsToSlugs from '../src/js/dataMapping/agency/agencyIdsToSlugs.js';
import { useStateNameByFipsId } from "../src/js/hooks/useStateData.jsx";
const { values: args } = parseArgs({
    options: {
        'agency-file': { type: 'string' },
        'output': { type: 'string', default: path.resolve(process.cwd(), 'redirects.conf') },
        'dry-run': { type: 'boolean', default: false },
    }
});

const outputPath = args['output'];

const legacyRedirects = [
    ['/Pages/Default.aspx/',                        '/'],
    //['/index.html',                                 '/'],
    ['/Pages/AdvancedSearch.aspx/',                 '/search'],
    ['/DownloadCenter/Pages/DataDownload.aspx/',    '/download_center/custom_award_data'],
    ['/DownloadCenter/Pages/dataarchives.aspx/',    '/download_center/award_data_archive'],
    ['/covid-19/',                                  '/disaster/covid-19'],
    ['/covid-19',                                   '/disaster/covid-19'],
    ['/analyst-guide',                              '/federal-spending-guide'],
    ['/analyst-guide/',                             '/federal-spending-guide'],
];


const stateRedirects = Object.entries(useStateNameByFipsId()).map(([fipsId, stateName]) => [
    `/state/${fipsId}`,
    `/state/${URLifyStateName(stateName)}`,
]);


const agencyRedirects = agencyIdsToSlugs.map((a) => [
    `/agency/${a.agency_id}`,
    `/agency/${a.agency_slug}`,
]);


const renderNginxConf = (legacy, states, agencies) => {
    const lines = [
        '# ---------------------------------------------------------------',
        '# Auto-generated by buildNginxRedirects.js — DO NOT EDIT',
        '# Include this file inside your nginx server {} block:',
        '#   include /etc/nginx/redirects.conf;',
        '# ---------------------------------------------------------------',
        '',
        '# --- Legacy redirects ---',
        // exact match (=) — fastest, no trailing-path ambiguity for fixed URLs
        ...legacy.map(([src, dst]) => `    location = ${src} { return 301 https://$host${dst}; }`),
        '',
        '# --- State FIPS → slug redirects ---',
        // prefix match (^~) — catches /state/01 and /state/01/anything
        ...states.map(([src, dst]) => `    location = ${src} { return 301 https://$host${dst}; }`),
        '',
        '# --- Agency ID → slug redirects ---',
        ...agencies.map(([src, dst]) => `    location = ${src} { return 301 https://$host${dst}; }`),
        '',
    ];

    return lines.join('\n');
};


const buildNginxRedirects = () => {
    const conf = renderNginxConf(legacyRedirects, stateRedirects, agencyRedirects);
    const total = legacyRedirects.length + stateRedirects.length + agencyRedirects.length;

    if (args['dry-run']) {
        console.log(conf);
        return;
    }

    const file = fs.createWriteStream(outputPath);
    file.write(conf);
    file.on('error', (e) => {
        console.error('Error writing redirects.conf:', e);
        throw e;
    });
    file.on('finish', () => {
        console.log(`Wrote ${total} redirect rules to '${outputPath}' (${legacyRedirects.length} legacy, ${stateRedirects.length} state, ${agencyRedirects.length} agency)`);
    });
    file.end();
};

buildNginxRedirects();