const tableSearchFields = {
    columnWidths: {
        award_id: 160,
        recipient_name: 310,
        period_of_performance_start_date: 150,
        period_of_performance_current_end_date: 150,
        total_obligation: 220,
        type: 230,
        awarding_agency_name: 280,
        awarding_subtier_name: 280,
        funding_agency_name: 280,
        funding_subtier_name: 280
    },
    defaultSortDirection: {
        award_id: 'asc',
        recipient_name: 'asc',
        period_of_performance_start_date: 'desc',
        period_of_performance_current_end_date: 'desc',
        total_obligation: 'desc',
        type: 'asc',
        awarding_agency_name: 'asc',
        awarding_subtier_name: 'asc',
        funding_agency_name: 'asc',
        funding_subtier_name: 'asc'
    },
    contracts: {
        _order: [
            'award_id',
            'recipient_name',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type',
            'awarding_agency_name',
            'awarding_subtier_name',
            'funding_agency_name',
            'funding_subtier_name'
        ],
        _requestFields: [
            'id',
            'piid',
            'fain',
            'uri',
            'recipient',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type_description',
            'awarding_agency',
            'funding_agency'
        ],
        _mapping: {
            award_id: 'piid',
            recipient_name: 'recipient__recipient_name',
            period_of_performance_start_date: 'period_of_performance_start_date',
            period_of_performance_current_end_date: 'period_of_performance_current_end_date',
            total_obligation: 'total_obligation',
            type: 'type',
            awarding_agency_name: 'awarding_agency__toptier_agency__name',
            awarding_subtier_name: 'awarding_agency__subtier_agency__name',
            funding_agency_name: 'funding_agency__toptier_agency__name',
            funding_subtier_name: 'funding_agency__subtier_agency__name'
        },
        award_id: 'Award ID',
        recipient_name: 'Recipient Name',
        period_of_performance_start_date: 'Start Date',
        period_of_performance_current_end_date: 'End Date',
        total_obligation: 'Total Funded To-Date',
        type: 'Award Type',
        awarding_agency_name: 'Awarding Agency',
        awarding_subtier_name: 'Awarding Sub-Agency',
        funding_agency_name: 'Funding Agency',
        funding_subtier_name: 'Funding Sub-Agency'
    },
    grants: {
        _order: [
            'award_id',
            'recipient_name',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type',
            'awarding_agency_name',
            'awarding_subtier_name',
            'funding_agency_name',
            'funding_subtier_name'
        ],
        _requestFields: [
            'id',
            'piid',
            'fain',
            'uri',
            'recipient',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type_description',
            'awarding_agency',
            'funding_agency'
        ],
        _mapping: {
            award_id: 'fain',
            recipient_name: 'recipient__recipient_name',
            period_of_performance_start_date: 'period_of_performance_start_date',
            period_of_performance_current_end_date: 'period_of_performance_current_end_date',
            total_obligation: 'total_obligation',
            type: 'type',
            awarding_agency_name: 'awarding_agency__toptier_agency__name',
            awarding_subtier_name: 'awarding_agency__subtier_agency__name',
            funding_agency_name: 'funding_agency__toptier_agency__name',
            funding_subtier_name: 'funding_agency__subtier_agency__name'
        },
        award_id: 'Award ID',
        recipient_name: 'Recipient Name',
        period_of_performance_start_date: 'Start Date',
        period_of_performance_current_end_date: 'End Date',
        total_obligation: 'Total Funded To-Date',
        type: 'Award Type',
        awarding_agency_name: 'Awarding Agency',
        awarding_subtier_name: 'Awarding Sub-Agency',
        funding_agency_name: 'Funding Agency',
        funding_subtier_name: 'Funding Sub-Agency'
    },
    direct_payments: {
        _order: [
            'award_id',
            'recipient_name',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type',
            'awarding_agency_name',
            'awarding_subtier_name',
            'funding_agency_name',
            'funding_subtier_name'
        ],
        _requestFields: [
            'id',
            'piid',
            'fain',
            'uri',
            'recipient',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type_description',
            'awarding_agency',
            'funding_agency'
        ],
        _mapping: {
            award_id: 'fain',
            recipient_name: 'recipient__recipient_name',
            period_of_performance_start_date: 'period_of_performance_start_date',
            period_of_performance_current_end_date: 'period_of_performance_current_end_date',
            total_obligation: 'total_obligation',
            type: 'type',
            awarding_agency_name: 'awarding_agency__toptier_agency__name',
            awarding_subtier_name: 'awarding_agency__subtier_agency__name',
            funding_agency_name: 'funding_agency__toptier_agency__name',
            funding_subtier_name: 'funding_agency__subtier_agency__name'
        },
        award_id: 'Award ID',
        recipient_name: 'Recipient Name',
        period_of_performance_start_date: 'Start Date',
        period_of_performance_current_end_date: 'End Date',
        total_obligation: 'Total Funded To-Date',
        type: 'Award Type',
        awarding_agency_name: 'Awarding Agency',
        awarding_subtier_name: 'Awarding Sub-Agency',
        funding_agency_name: 'Funding Agency',
        funding_subtier_name: 'Funding Sub-Agency'
    },
    loans: {
        _order: [
            'award_id',
            'recipient_name',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'type',
            'awarding_agency_name',
            'awarding_subtier_name',
            'funding_agency_name',
            'funding_subtier_name'
        ],
        _requestFields: [
            'id',
            'piid',
            'fain',
            'uri',
            'recipient',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type_description',
            'awarding_agency',
            'funding_agency'
        ],
        _mapping: {
            award_id: 'fain',
            recipient_name: 'recipient__recipient_name',
            period_of_performance_start_date: 'period_of_performance_start_date',
            period_of_performance_current_end_date: 'period_of_performance_current_end_date',
            total_obligation: 'total_obligation',
            type: 'type',
            awarding_agency_name: 'awarding_agency__toptier_agency__name',
            awarding_subtier_name: 'awarding_agency__subtier_agency__name',
            funding_agency_name: 'funding_agency__toptier_agency__name',
            funding_subtier_name: 'funding_agency__subtier_agency__name'
        },
        award_id: 'Award ID',
        recipient_name: 'Recipient Name',
        period_of_performance_start_date: 'Start Date',
        period_of_performance_current_end_date: 'End Date',
        type: 'Award Type',
        awarding_agency_name: 'Awarding Agency',
        awarding_subtier_name: 'Awarding Sub-Agency',
        funding_agency_name: 'Funding Agency',
        funding_subtier_name: 'Funding Sub-Agency'
    },
    insurance: {
        _order: [
            'award_id',
            'recipient_name',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type',
            'awarding_agency_name',
            'awarding_subtier_name',
            'funding_agency_name',
            'funding_subtier_name'
        ],
        _requestFields: [
            'id',
            'piid',
            'fain',
            'uri',
            'recipient',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'total_obligation',
            'type_description',
            'awarding_agency',
            'funding_agency'
        ],
        _mapping: {
            award_id: 'fain',
            recipient_name: 'recipient__recipient_name',
            period_of_performance_start_date: 'period_of_performance_start_date',
            period_of_performance_current_end_date: 'period_of_performance_current_end_date',
            total_obligation: 'total_obligation',
            type: 'type',
            awarding_agency_name: 'awarding_agency__toptier_agency__name',
            awarding_subtier_name: 'awarding_agency__subtier_agency__name',
            funding_agency_name: 'funding_agency__toptier_agency__name',
            funding_subtier_name: 'funding_agency__subtier_agency__name'
        },
        award_id: 'Award ID',
        recipient_name: 'Recipient Name',
        period_of_performance_start_date: 'Start Date',
        period_of_performance_current_end_date: 'End Date',
        total_obligation: 'Total Funded To-Date',
        type: 'Award Type',
        awarding_agency_name: 'Awarding Agency',
        awarding_subtier_name: 'Awarding Sub-Agency',
        funding_agency_name: 'Funding Agency',
        funding_subtier_name: 'Funding Sub-Agency'
    }
};

export default tableSearchFields;
