name: Run Broken Link Checker

on:
  workflow_call:
    #schedule:
    #    - cron:  '12 1 * * 5'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - name: Run Broken Links Checker
        run: npx broken-link-checker $WEBSITE_URL --ordered --recursive \
          --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"