name: Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

# Only allow a single run of the PR checks for each branch. This means that in the case of multiple
# PRs opened from a single branch into multiple others (e.g., hotfixes) a single run of the PR checks
# will occur. However, additional runs of the PR checks will be triggered when the source branch
# is re-synced with the target branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # There isn't a good way to avoid running a workflow when a Draft PR is opened. As a result, we
  # first check if a Draft PR triggered this workflow and cancel the workflow if that is the case.
  Cancel-If-Draft-Pull-Request:
    if: github.event.pull_request.draft == true
    uses: ./.github/workflows/cancel-running-workflow.yaml

  # The conditional in each of the workflows below is required. Without these checks they will be skipped
  # when the "Cancel-If-Draft-Pull-Request" workflow is skipped.
  Run-Setup-Env:
    name: Run Setup Environment
    needs: Cancel-If-Draft-Pull-Request
    if: |
      always() &&
      needs.Cancel-If-Draft-Pull-Request.result == 'skipped'
    uses: ./.github/workflows/setup-env.yaml

  # The test suite is broken into multiple groups based on a combination of what is under test
  # and the time that it takes to run tests for that group.
  Run-Unit-Tests:
    name: Run Unit Tests
    needs: Run-Setup-Env
    if: ${{ !failure() && !cancelled() }}
    uses: ./.github/workflows/test-unit.yaml
    with:
      working-directory: usaspending-website