name: Audit, Jest, Linting
# run audit and jest
on:
  workflow_call:

jobs:
  Run:
    # These checks are not broken out into multiple jobs because the steps to prepare the environment
    # take the bulk of the time. Running them in parallel saves minimal time at the cost of using more
    # runners than needed.
    name: Audit, Jest, Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"

      - name: Init NPM
        run: npm install -g npm@10.8.3

      - name: Install webpack
        run: npm install -g webpack@5.94.0

      - name: Install webpack cli
        run: npm install -g webpack-cli@5.1.4

      - name: Run NPM install
        run: npm ci --legacy-peer-deps --timeout=90000

      - name: Run Audit command
        run: npm run auditLintTest
     